name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_EXTERNAL_IP }} >> ~/.ssh/known_hosts

    - name: Connect and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa tomer@${{ secrets.VM_EXTERNAL_IP }} << 'EOF'
          cd /home/tomer
          rm -rf Stats
          git clone https://github.com/TomerTTB/Stats.git
          cd Stats
          npm install
          # pm2 start npm --name stats-app -- start || pm2 restart stats-app
        EOF